"""auto

Revision ID: 8462d33c6d64
Revises: e458588aa95d
Create Date: 2026-04-12 15:15:21.881853

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8462d33c6d64"
down_revision: Union[str, Sequence[str], None] = "e458588aa95d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "aircraft",
        sa.Column(
            "last_100hr_inspection_hobbs",
            sa.Float(),
            nullable=False,
            server_default="0.0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aircraft", "last_100hr_inspection_hobbs")
    # ### end Alembic commands ###
