"""init

Revision ID: b1ccf4e21bff
Revises:
Create Date: 2026-04-11 12:28:53.270092

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1ccf4e21bff"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clubs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("home_base", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clubs_id"), "clubs", ["id"], unique=False)
    op.create_table(
        "aircraft",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("tail_number", sa.String(length=10), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("hourly_rate_usd", sa.Float(), nullable=False),
        sa.Column("total_hobbs_hours", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("available", "maintenance", "retired", name="aircraftstatus"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_aircraft_club_id"), "aircraft", ["club_id"], unique=False)
    op.create_index(op.f("ix_aircraft_id"), "aircraft", ["id"], unique=False)
    op.create_index(
        op.f("ix_aircraft_tail_number"), "aircraft", ["tail_number"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("member", "instructor", "admin", name="userrole"),
            nullable=False,
        ),
        sa.Column(
            "certificate",
            sa.Enum("student", "private", "commercial", "atp", name="certificatetype"),
            nullable=True,
        ),
        sa.Column("ratings", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_club_id"), "users", ["club_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "maintenance_windows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("aircraft_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.id"],
        ),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_maintenance_windows_aircraft_id"),
        "maintenance_windows",
        ["aircraft_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_windows_club_id"),
        "maintenance_windows",
        ["club_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maintenance_windows_id"), "maintenance_windows", ["id"], unique=False
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=False),
        sa.Column("aircraft_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("instructor_id", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("confirmed", "cancelled", "completed", name="reservationstatus"),
            nullable=False,
        ),
        sa.Column("hobbs_start", sa.Float(), nullable=True),
        sa.Column("hobbs_end", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_time > start_time", name="ck_reservation_end_after_start"
        ),
        sa.CheckConstraint("hobbs_end > hobbs_start", name="ck_hobbs_end_after_start"),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.id"],
        ),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reservations_aircraft_id"),
        "reservations",
        ["aircraft_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reservations_club_id"), "reservations", ["club_id"], unique=False
    )
    op.create_index(op.f("ix_reservations_id"), "reservations", ["id"], unique=False)
    op.create_index(
        op.f("ix_reservations_instructor_id"),
        "reservations",
        ["instructor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reservations_member_id"), "reservations", ["member_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reservations_member_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_instructor_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_club_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_aircraft_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(op.f("ix_maintenance_windows_id"), table_name="maintenance_windows")
    op.drop_index(
        op.f("ix_maintenance_windows_club_id"), table_name="maintenance_windows"
    )
    op.drop_index(
        op.f("ix_maintenance_windows_aircraft_id"), table_name="maintenance_windows"
    )
    op.drop_table("maintenance_windows")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_club_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_aircraft_tail_number"), table_name="aircraft")
    op.drop_index(op.f("ix_aircraft_id"), table_name="aircraft")
    op.drop_index(op.f("ix_aircraft_club_id"), table_name="aircraft")
    op.drop_table("aircraft")
    op.drop_index(op.f("ix_clubs_id"), table_name="clubs")
    op.drop_table("clubs")
    # ### end Alembic commands ###
